# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "angular-upgrade_core" ]
  pull_request:
    branches: [ "angular-upgrade_core" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate Lines of Code
        id: loc
        uses: PavanMudigonda/lines-of-code-reporter@v1.5
        with:
          directory: "./src/app/_app/weather-app/ " #Optional #Comma Seperated
          include_ext: "ts"                         #Optional # Comma Seperated
          exclude_dir: "node_modules,.github"       #Optional # Comma Seperated
          exclude_ext: "sh"                         #Optional # Comma Seperated
      - name: print output
        shell: pwsh
        run: | 
          Write-Host 'Total Lines of Code...:  ${{ steps.lines-of-code-reporter.outputs.total_lines }}'
          Write-Host 'Lines of Code Markdown Report Path...:  ${{ steps.lines-of-code-reporter.outputs.loc_report }}'
      # Publish Lines of Code Summary  # Optional
      - name: Add Lines of Code Summary
        run: echo "${{ steps.loc.outputs.lines-of-code-summary }}" >> $GITHUB_STEP_SUMMARY
